### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by papjul**
French translation completed, tested with a debug build.
(I also fixed a copy/paste error in English translation)

A few issues encountered on app side:
- Search bar placeholder is cut, instead of being ellipsed (the last word of "Rechercher des emplacements" is cut at "des" instead of "emplacements" being ellipsed). We could make it slightly shorter by writing "Search for place" singular instead of "Search for places" plural)
- Open-Meteo search results are in English (shows "Germany" instead of "Allemagne")
- Days of the week are in English in the daily card on main screen
- Numbers formatted with the English (US) locale instead of French (shows 1,003 hPa instead of 1 003 hPa, or 0.1 km instead of 0,1 km)

App was force closed/restarted before being tested

I also recommand you [generate your `locales_config.xml` dynamically](https://github.com/breezy-weather/breezy-weather/blob/v5.2.0/buildSrc/src/main/kotlin/LocalesConfigPlugin.kt) for easier maintenance.

### CODE REVIEW

**Comment by davidtakac** [comment]
Thanks for this, looks great!

Regarding the issues: 
- I fixed the placeholder being cut by ellipsizing it.
- Non-localised Open-Meteo search results, days of the week and numbers were all fixed by adding `Locale.forLanguageTag("fr")` into `supportedLocales` in `common/Locale.kt`. This is to avoid situations where someone's system language is German, but the app has not been translated into German, so it displays a mix of English strings and German numbers and days of the week. This way everything falls back to Locale.US when a language is not supported yet.
- I'll take a look at the automatic `locales_config.xml` generation, thanks! I'll have to see if there's a way to automatically add the new locale into supportedLocales as well.

Open topics: 
- Although ellipsizing the search bar placeholder works, is there a more concise way to say "Search for places" in French while being relatively grammatically correct? For example, in English, I put "Search places" which passes, but is probably not **the** most grammatically correct.
- The up and down arrows instead of H and L look odd to me and are not consistent with the English localisation. Would it make sense to put something like "H:%s B:%s" in French? Going by "High, Low" being translated as "Haut, Bas" by Google Translate.
- I see "Today" was translated as "Auj." but the days of the week are lowercase ("sam.", "dim.", etc.) Should "Auj." be lowercase, too? In Croatian the days of the week are lowercased and so is "danas", which is the word for "Today".

**Comment by papjul** [comment]
> Although ellipsizing the search bar placeholder works, is there a more concise way to say "Search for places" in French while being relatively grammatically correct? For example, in English, I put "Search places" which passes, but is probably not the most grammatically correct.

Just "Rechercher" which means "Search". We can say "Rechercher des lieux" but it wouldn't be consistent with the translation for "place" in other places, and replacing "place" with "lieu" everywhere else doesn't sound very good in French IMO (at least in a well-translated weather app).

> The up and down arrows instead of H and L look odd to me and are not consistent with the English localisation. Would it make sense to put something like "H:%s B:%s" in French? Going by "High, Low" being translated as "Haut, Bas" by Google Translate.

No one uses these abbreviations in French. The arrows are common in weather apps in my experience, more than H and L that I had to find in context to understand what it meant. If you want to keep a word, we say Maximum/Minimum in French, not High/Low. We also need appropriate typography with spacing around both sides of the colon, e.g. `Max : %s` and `Min : %s`.

> I see "Today" was translated as "Auj." but the days of the week are lowercase ("sam.", "dim.", etc.) Should "Auj." be lowercase, too? In Croatian the days of the week are lowercased and so is "danas", which is the word for "Today".

The days of the week are not capitalized if they are in the middle of a sentence. If it's standing alone or at the beginning of a sentence, it is capitalized.

**Comment by papjul** [comment]
This is exactly what Apple does with the French translation (I didn't even check this app when translating, it just felt natural to me), both for high/low and days of the week. However, they translated "Now" as "Maint." abbreviation of "Maintenant" but although it is the direct translation, "Actuel" for "Current" feels better IMO.
apple-en
apple-fr

**Comment by davidtakac** [comment]
> Just "Rechercher" which means "Search". We can say "Rechercher des lieux" but it wouldn't be consistent with the translation for "place" in other places, and replacing "place" with "lieu" everywhere else doesn't sound very good in French IMO (at least in a well-translated weather app).

Understood. I'm happy with the original translation then.

> No one uses these abbreviations in French. The arrows are common in weather apps in my experience, more than H and L that I had to find in context to understand what it meant. If you want to keep a word, we say Maximum/Minimum in French, not High/Low. We also need appropriate typography with spacing around both sides of the colon, e.g. Max : %s and Min : %s.

Those abbreviations are not used in Croatian either. I think I'd rather have arrows in English, too. The problem with the textual arrows is that they look skinny. I'll try replacing them with up and down vector icons for all languages.

> The days of the week are not capitalized if they are in the middle of a sentence. If it's standing alone or at the beginning of a sentence, it is capitalized.

Same for Croatian, actually. I'll fix this.

**Pull request merged**
